#define UI_RE_WINNER_1 0
#define UI_RE_WINNER_2 19
#define UI_RE_TIE 38
#define UI_MM_1_PLAYER 52
#define UI_MM_2_PLAYERS 66
#define UI_MM_OPTIONS 78
#define UI_MM_TEST 92
#define UI_OM_LANGUAGE 99
#define UI_OM_BACK 115
#define UI_SM_BEAT_GULLEROD 123
#define UI_CS_SELECT_1_CHARACTER 173
#define UI_CS_SELECT_2_CHARACTERS 190
#define UI_CH_NISSE_NAME 208
#define UI_CH_GULLEROD_NAME 215
#define UI_AT_PRESS_START 229
#define UI_EMPTY_STRING 241
#define UI_LANG_DA 241
#define UI_LANG_EN 247
#define UI_LANG_ES 255
const int language_size = 264;
extern char translation_contents;
